os:       linux
dist:     bionic
language: cpp
compiler: gcc

# TBD why??? if: branch IN (master , development)

before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y build-dep freewheeling
  # build-dep is not sufficient, we need to explicitly install liblo-dev
  - sudo apt-get -y install liblo-dev doxygen graphviz

script:
  - autoreconf -if
  - ./configure
  - make
  - sudo make install
  - make installcheck

  # Documentation
  - doxygen

# Generate and deploy documentation
deploy:
  provider: pages
  strategy: git
  cleanup: false
  local_dir: html
  token: $GH_REPO_TOKEN
  on:
    branch: ci-doxygen  # TBD for now

